### ISSUE TITLE
Missing LFS files

### ISSUE THREAD

**Issue by mathstuf** [CtopCsUtahEdu/bricklib#7]
In commit 484970705f0493110991230bd613773909294e07 (by @Sam3077), two images were added that should be stored in LFS, but they are not available on the Github repository. This causes failures to build in Spack when using Git. FWIW, it was merged via commit 484970705f0493110991230bd613773909294e07.

Wherever these files live, `git lfs push --all $remote_for_github` (guessing because the commit messages reference issue/PR ids that don't exist here, so I assume there is some other development platform in use) should be able to resolve it.

**Comment by mathstuf** [comment]
Pinging @ztuowen since it appears that you reviewed the PR that merged the addition (in case you have the files).

**Comment by ztuowen** [comment]
Thank you for bringing it up. I have uploaded those files. Please check.

**Comment by mathstuf** [comment]
Spack is able to fetch the sources and build now, thanks!
